### ISSUE TITLE
老哥稳 666，问个小问题怎么扩大图库

### ISSUE THREAD

**Issue by aizigao** [frapples/hexo-article-emoji#1]
![image](https://cloud.githubusercontent.com/assets/14126445/23395155/11c84578-fdc8-11e6-9c08-41a4aca63dc1.png)
好多表情还没有的说

**Comment by frapples** [comment]
抱歉这段时间没看github，刚刚看到。
我这个里面带了完整版的表情的，你看readme.org就知道了：
```
hexo article-emoji install full
```
上面的命令将完整版的表情复制到你的source/images文件夹里去。

然后改下配置，启用完整版的表情，编辑_config.yml，加入:
```
article_emoji:
  full: true
```
完整版一共有872个表情，觉得应该是很全了。。。。

**Comment by aizigao** [comment]
好吧
